apiVersion: v1
kind: Secret
metadata:
  name: multi-cluster-secrets
  namespace: multi-cluster-kafka
  labels:
    app.kubernetes.io/name: multi-cluster-kafka-manager
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=  # redis_password
  SECRET_KEY: c3VwZXJfc2VjcmV0X2tleV9mb3JfcHJvZHVjdGlvbg==  # super_secret_key_for_production
  GRAFANA_PASSWORD: Z3JhZmFuYV9hZG1pbl9wYXNzd29yZA==  # grafana_admin_password
  
  # AWS credentials for backups (if using S3)
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  BACKUP_S3_BUCKET: ""
  
  # SSL certificates (if using HTTPS)
  TLS_CERT: ""
  TLS_KEY: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: multi-cluster-kafka
  labels:
    app.kubernetes.io/name: multi-cluster-kafka-manager
    app.kubernetes.io/component: database
type: Opaque
data:
  POSTGRES_DB: bXVsdGlfY2x1c3Rlcl9kYg==  # multi_cluster_db
  POSTGRES_USER: a2Fma2FfdXNlcg==  # kafka_user
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password