# Production environment configuration
environment: production
debug: false

api:
  reload: false
  host: "0.0.0.0"
  port: 8000

monitoring:
  log_level: "INFO"
  health_check_interval: 30
  enable_metrics: true

kafka:
  bootstrap_servers: "localhost:9092"
  request_timeout_ms: 30000
  connection_timeout_ms: 10000
  default_partitions: 3
  default_replication_factor: 1

kafka_rest_proxy:
  host: "localhost"
  port: 8082
  request_timeout: 60
  max_retries: 5
  retry_delay: 2.0

kafka_ui:
  host: "localhost"
  port: 8080
  cluster_name: "local-prod"
  dynamic_config_enabled: true

docker:
  compose_file: "docker-compose.yml"
  project_name: "local-kafka-manager"
  network_name: "kafka-network"
  container_start_timeout: 180
  container_stop_timeout: 60